import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Expense, ExpenseForm } from "../components/ExpenseForm";

const Home: NextPage = () => {
  const handleSubmit = (expense: Expense) => {
    console.log(`Enviou as coisas`, expense);
  };
  return (
    <div>
      <Head>
        <title>Calculadora de gastos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Calculadora de gastos</h1>
        <ExpenseForm onSubmit={handleSubmit} />
      </main>
    </div>
  );
};

export default Home;
