import type { NextPage } from "next";
import Head from "next/head";
import { Expense, ExpenseForm } from "../components/ExpenseForm";
import Link from "next/link";

const Home: NextPage = () => {
  const handleSubmit = (expense: Expense) => {
    const previousExpenses: Expense[] = JSON.parse(
      localStorage.getItem("savedExpenses") || "[]"
    );
    const currentExpenses = previousExpenses.concat(expense);
    localStorage.setItem("savedExpenses", JSON.stringify(currentExpenses));
    console.log(`Enviou as coisas`, currentExpenses);
  };
  return (
    <div>
      <Head>
        <title>Calculadora de gastos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Calculadora de gastos</h1>
        <ExpenseForm onSubmit={handleSubmit} />
        <Link href="/expenses">
          <a>Lista de gastos</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
